# Generated by Django 2.2.24 on 2021-11-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='genero',
            field=models.CharField(max_length=25),
        ),
    ]
