# Generated by Django 2.2.24 on 2021-11-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0002_auto_20211103_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('turno', models.CharField(max_length=50)),
                ('estudiantes', models.ManyToManyField(related_name='EstudiantesClase', to='estudiante.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantesClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clase.Clase')),
                ('estudiantes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiante.Estudiante')),
            ],
        ),
    ]
