# Generated by Django 2.2.24 on 2021-11-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudiantesClase',
        ),
    ]
